=== Donders-Institute/RADAR-REDCap-aRMT-Definitions/docs/questionnaire-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://radar-base.org/armt/definitions/schema#",
  "type": "array",
  "title": "The Root Schema",
  "description": "An explanation about the purpose of this instance.",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "description": "An explanation about the purpose of this instance.",
    "required": [
      "field_name",
      "form_name",
      "section_header",
      "field_type",
      "field_label",
      "select_choices_or_calculations",
      "field_note",
      "text_validation_type_or_show_slider_number",
      "text_validation_min",
      "text_validation_max",
      "identifier",
      "branching_logic",
      "required_field",
      "custom_alignment",
      "question_number",
      "matrix_group_name",
      "matrix_ranking",
      "field_annotation",
      "evaluated_logic"
    ],
    "properties": {
      "field_name": {
        "$id": "#/items/properties/field_name",
        "type": "string",
        "title": "The Field_name Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "esm_content"
        ],
        "pattern": "^(.*)$"
      },
      "form_name": {
        "$id": "#/items/properties/form_name",
        "type": "string",
        "title": "The Form_name Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "esm"
        ],
        "pattern": "^(.*)$"
      },
      "section_header": {
        "$id": "#/items/properties/section_header",
        "type": "string",
        "title": "The Section_header Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ]
      },
      "field_type": {
        "$id": "#/items/properties/field_type",
        "type": "string",
        "title": "The Field_type Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "range"
        ],
        "pattern": "^(.*)$"
      },
      "field_label": {
        "$id": "#/items/properties/field_label",
        "type": "string",
        "title": "The Field_label Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Right now, I feel content"
        ]
      },
      "select_choices_or_calculations": {
        "$id": "#/items/properties/select_choices_or_calculations",
        "type": "array",
        "title": "The Select_choices_or_calculations Schema",
        "description": "An explanation about the purpose of this instance.",
        "items": {
          "$id": "#/items/properties/select_choices_or_calculations/items",
          "type": "object",
          "title": "The Items Schema",
          "description": "An explanation about the purpose of this instance.",
          "required": [
            "code",
            "label"
          ],
          "properties": {
            "code": {
              "$id": "#/items/properties/select_choices_or_calculations/items/properties/code",
              "type": "string",
              "title": "The Code Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": [
                "1"
              ],
              "pattern": "^(.*)$"
            },
            "label": {
              "$id": "#/items/properties/select_choices_or_calculations/items/properties/label",
              "type": "string",
              "title": "The Label Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": [
                "1 Not at all"
              ],
              "pattern": "^(.*)$"
            }
          },
          "additionalProperties": false
        }
      },
      "field_note": {
        "$id": "#/items/properties/field_note",
        "type": "string",
        "title": "The Field_note Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "text_validation_type_or_show_slider_number": {
        "$id": "#/items/properties/text_validation_type_or_show_slider_number",
        "type": "string",
        "title": "The Text_validation_type_or_show_slider_number Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "text_validation_min": {
        "$id": "#/items/properties/text_validation_min",
        "type": "string",
        "title": "The Text_validation_min Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "text_validation_max": {
        "$id": "#/items/properties/text_validation_max",
        "type": "string",
        "title": "The Text_validation_max Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "identifier": {
        "$id": "#/items/properties/identifier",
        "type": "string",
        "title": "The Identifier Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "branching_logic": {
        "$id": "#/items/properties/branching_logic",
        "type": "string",
        "title": "The Branching_logic Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "required_field": {
        "$id": "#/items/properties/required_field",
        "type": "string",
        "title": "The Required_field Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "custom_alignment": {
        "$id": "#/items/properties/custom_alignment",
        "type": "string",
        "title": "The Custom_alignment Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "question_number": {
        "$id": "#/items/properties/question_number",
        "type": "string",
        "title": "The Question_number Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "matrix_group_name": {
        "$id": "#/items/properties/matrix_group_name",
        "type": "string",
        "title": "The Matrix_group_name Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "esm1"
        ],
        "pattern": "^(.*)$"
      },
      "matrix_ranking": {
        "$id": "#/items/properties/matrix_ranking",
        "type": "string",
        "title": "The Matrix_ranking Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "field_annotation": {
        "$id": "#/items/properties/field_annotation",
        "title": "The Field_annotation Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": ""
      },
      "evaluated_logic": {
        "$id": "#/items/properties/evaluated_logic",
        "type": "string",
        "title": "The Evaluated_logic Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      }
    },
    "additionalProperties": false
  }
}

=== Donders-Institute/RADAR-REDCap-aRMT-Definitions/questionnaires/2MW_test/2MW_test_armt_it.json
[
 {
     "field_name": "2MW_test_1",
     "form_name": "2MW_test",
     "section_header": "2MW Test",
     "field_type": "info",
     "field_label": "",
     "select_choices_or_calculations": [ {
       "label" : "Trovi un percorso con una distanza di 10 metri dove può facilmente camminare avanti e indietro.",
       "code" : "Parte 1"
     }, {
       "label" : "Una volta indossata la cintura intorno al torace cammini avanti e indietro per 2 minuti fino a quando il cellulare indicherà di fermarsi.",
       "code" : "Parte 2"
     }, {
       "label" : "Si senta libero di interrompere il cammino nel caso avesse bisogno di riposarsi.",
       "code" : "Parte 3"
     }, {
       "label" : "Prema ‘Successivo’ per iniziare.",
       "code" : "Parte 4"
     } ],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "2MW",
     "matrix_ranking": "",
     "field_annotation": "",
     "evaluated_logic": ""
 },
 {
     "field_name": "2MW_test_2",
     "form_name": "2MW_test",
     "section_header": "2MW Test",
     "field_type": "timed",
     "field_label": "Inizi a camminare avanti e indietro.",
     "select_choices_or_calculations": [],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "2MW",
     "matrix_ranking": "",
     "field_annotation": {
       "image" : "assets/imgs/2MWT_walking.png",
       "timer" : {
         "start": 120,
         "end": 0
       },
       "unit" : "sec"
     },
     "evaluated_logic": ""
 }
]

=== Donders-Institute/RADAR-REDCap-aRMT-Definitions/questionnaires/2MW_test/2MW_test_armt.json
[
 {
     "field_name": "2MW_test_1",
     "form_name": "2MW_test",
     "section_header": "2MW Test",
     "field_type": "info",
     "field_label": "",
     "select_choices_or_calculations": [ {
       "label" : "Make yourself comfortable, and in standing position. Your feet should be together and your hands by your side.",
       "code" : "Part 1"
     }, {
       "label" : "Press the start button. A timer will count down the seconds.",
       "code" : "Part 2"
     }, {
       "label" : "After 10 seconds, a beep will alert you to continue the exercise with your eyes closed.",
       "code" : "Part 3"
     } ],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "romberg",
     "matrix_ranking": "",
     "field_annotation": "",
     "evaluated_logic": ""
 },
 {
     "field_name": "2MW_test_2",
     "form_name": "2MW_test",
     "section_header": "2MW Test",
     "field_type": "timed",
     "field_label": "Start walking back and forth.",
     "select_choices_or_calculations": [],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "romberg",
     "matrix_ranking": "",
     "field_annotation": {
       "image" : "assets/imgs/2MWT_walking.png",
       "timer" : {
         "start": 120,
         "end": 0
       },
       "unit" : "sec"
     },
     "evaluated_logic": ""
 }
]

=== Donders-Institute/RADAR-REDCap-aRMT-Definitions/questionnaires/romberg_test/romberg_test_armt_it.json
[
 {
     "field_name": "romberg_1",
     "form_name": "romberg_test",
     "section_header": "Romberg's Test",
     "field_type": "info",
     "field_label": "",
     "select_choices_or_calculations": [ {
       "label" : "Si metta comodo e si metta in piedi. Unisca i piedi e distenda le braccia lungo i fianchi.",
       "code" : "Parte 1"
     }, {
       "label" : "Schiacci il bottone ‘Successivo’. Un cronometro conterà i secondi.",
       "code" : "Parte 2"
     }, {
       "label" : "Dopo 10 secondi, un ‘beep’ la avviserà di continuare l’esercizio con gli occhi chiusi.",
       "code" : "Parte 3"
     } ],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "romberg",
     "matrix_ranking": "",
     "field_annotation": "",
     "evaluated_logic": ""
 },
 {
     "field_name": "romberg_2",
     "form_name": "romberg_test",
     "section_header": "Romberg's Test",
     "field_type": "timed",
     "field_label": "Tenga gli occhi aperti",
     "select_choices_or_calculations": [],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "romberg",
     "matrix_ranking": "",
     "field_annotation": {
       "image" : "assets/imgs/eyesopen.png",
       "timer" : {
         "start": 20,
         "end": 11
       },
       "unit" : "sec"
     },
     "evaluated_logic": ""
 },
 {
     "field_name": "romberg_3",
     "form_name": "romberg_test",
     "section_header": "Romberg's Test",
     "field_type": "timed",
     "field_label": "Chiuda gli occhi",
     "select_choices_or_calculations": [],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "romberg",
     "matrix_ranking": "",
     "field_annotation": {
       "image" : "assets/imgs/eyesclosed.png",
       "timer" : {
         "start": 10,
         "end": 0
       },
       "unit" : "sec"
     },
     "evaluated_logic": ""
 }
]

=== Donders-Institute/RADAR-REDCap-aRMT-Definitions/questionnaires/tandem_walking_test/tandem_walking_test_armt_it.json
[
 {
     "field_name": "tandem_walking_test_1",
     "form_name": "tandem_walking_test",
     "section_header": "Tandem Walking Test",
     "field_type": "info",
     "field_label": "",
     "select_choices_or_calculations": [ {
       "label" : "Si metta in piedi. Unisca i piedi e distenda le braccia lungo i fianchi.",
       "code" : "Parte 1"
     }, {
       "label" : "Compia 10 passi in linea retta. Ad ogni passo posizioni il piede modo tale che il tallone tocchi la punta del piede che sta dietro. (Come se camminasse su una fune).",
       "code" : "Parte 2"
     }, {
       "label" : "Clicchi ‘Successivo’ per iniziare, una volta completati i 10 passi, clicchi ‘Fine’ per terminare il test.",
       "code" : "Parte 3"
     } ],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "tandem_walking_test",
     "matrix_ranking": "",
     "field_annotation": "",
     "evaluated_logic": ""
 },
 {
     "field_name": "tandem_walking_test_2",
     "form_name": "tandem_walking_test",
     "section_header": "Tandem Walking Test",
     "field_type": "info",
     "field_label": "",
     "select_choices_or_calculations": [ {
       "label" : "Clicchi ‘Fine’ una volta effettuati i 10 passi.",
       "code" : "Parte 1"
     } ],
     "field_note": "",
     "text_validation_type_or_show_slider_number": "",
     "text_validation_min": "",
     "text_validation_max": "",
     "identifier": "",
     "branching_logic": "",
     "required_field": "",
     "custom_alignment": "",
     "question_number": "",
     "matrix_group_name": "tandem_walking_test",
     "matrix_ranking": "",
     "field_annotation": "",
     "evaluated_logic": ""
 }
]

=== Donders-Institute/RADAR-REDCap-aRMT-Definitions/questionnaires/audio/audio_armt.json
[
  {
    "field_name": "audio_1",
    "form_name": "audio",
    "section_header": "Speech test",
    "field_type": "info",
    "field_label": "Read this carefully!",
    "select_choices_or_calculations": [
      {
        "label" : "Make yourself comfortable, and find a quiet space.",
        "code" : "Step 1"
      }, {
        "label" : "The next screen will show you a short paragraph to read aloud. The app will record your voice while you do so.",
        "code" : "Part 2"
      }, {
        "label" : "Click 'next' to get started",
        "code" : "Part 3"
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "audio",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
  },
  {
    "field_name": "audio_2",
    "form_name": "audio",
    "section_header": "Speech test",
    "field_type": "audio",
    "field_label":"",
    "select_choices_or_calculations": [
      {
        "label" : "Go placidly amid the noise and haste, and remember what peace there may be in silence. As far as possible, without surrender, be on good terms with all persons. Speak your truth quietly and clearly; and listen to others, even to the dull and ignorant; they too have their story.",
        "code" : "P1"
      }, {
        "label" : "Avoid loud and aggressive persons, they are vexations to the spirit. If you compare yourself with others, you may become vain and bitter, for always there will be greater and lesser persons than yourself. Enjoy your achievements as well as your plans.",
        "code" : "P2"
      }, {
        "label" : "Keep interested in your own career, however humble; it is a real possession in the changing fortunes of time. Exercise caution in your business affairs, for the world is full of trickery. But let this not blind you to what virtue there is; many persons strive for high ideals, and everywhere life is full of heroism.",
        "code" : "P3"
      }
    ],
    "field_note": "",
    "text_validation_type_or_show_slider_number": "",
    "text_validation_min": "",
    "text_validation_max": "",
    "identifier": "",
    "branching_logic": "",
    "required_field": "",
    "custom_alignment": "",
    "question_number": "",
    "matrix_group_name": "audio",
    "matrix_ranking": "",
    "field_annotation": "",
    "evaluated_logic": ""
   }
]
